// Code generated from GitHub's OpenAPI description by internal/restfilter/gen. DO NOT EDIT.

package restfilter

// repoEnumOps maps "GET /path/{tmpl}" to the JSON locations of repository identities in
// its response, so the filter can drop denied-repo data wherever it appears.
var repoEnumOps = map[string][]string{
	"GET /assignments/{assignment_id}":                      {"$.starter_code_repository.full_name"},
	"GET /assignments/{assignment_id}/accepted_assignments": {"$[].assignment.classroom.name", "$[].repository.full_name"},
	"GET /classrooms": {"$[].name"},
	"GET /classrooms/{classroom_id}/assignments":                                                 {"$[].classroom.name"},
	"GET /enterprises/{enterprise}/code-security/configurations/{configuration_id}/repositories": {"$[].repository.full_name"},
	"GET /enterprises/{enterprise}/dependabot/alerts":                                            {"$[].repository.full_name"},
	"GET /enterprises/{enterprise}/dependabot/repository-access":                                 {"$.accessible_repositories[].full_name"},
	"GET /events":                                                                                  {"$[].payload.issue.repository.full_name", "$[].repo.name"},
	"GET /installation/repositories":                                                               {"$.repositories[].full_name"},
	"GET /issues":                                                                                  {"$[].repository.full_name"},
	"GET /networks/{owner}/{repo}/events":                                                          {"$[].payload.issue.repository.full_name", "$[].repo.name"},
	"GET /notifications":                                                                           {"$[].repository.full_name"},
	"GET /notifications/threads/{thread_id}":                                                       {"$.repository.full_name"},
	"GET /orgs/{org}/actions/cache/usage-by-repository":                                            {"$.repository_cache_usages[].full_name"},
	"GET /orgs/{org}/actions/permissions/repositories":                                             {"$.repositories[].full_name"},
	"GET /orgs/{org}/actions/permissions/self-hosted-runners/repositories":                         {"$.repositories[].full_name"},
	"GET /orgs/{org}/actions/runner-groups/{runner_group_id}/repositories":                         {"$.repositories[].full_name"},
	"GET /orgs/{org}/actions/secrets/{secret_name}/repositories":                                   {"$.repositories[].full_name"},
	"GET /orgs/{org}/actions/variables/{name}/repositories":                                        {"$.repositories[].full_name"},
	"GET /orgs/{org}/agents/secrets/{secret_name}/repositories":                                    {"$.repositories[].full_name"},
	"GET /orgs/{org}/agents/variables/{name}/repositories":                                         {"$.repositories[].full_name"},
	"GET /orgs/{org}/code-scanning/alerts":                                                         {"$[].repository.full_name"},
	"GET /orgs/{org}/code-security/configurations/{configuration_id}/repositories":                 {"$[].repository.full_name"},
	"GET /orgs/{org}/codespaces":                                                                   {"$.codespaces[].repository.full_name"},
	"GET /orgs/{org}/codespaces/secrets/{secret_name}/repositories":                                {"$.repositories[].full_name"},
	"GET /orgs/{org}/copilot/coding-agent/permissions/repositories":                                {"$.repositories[].full_name"},
	"GET /orgs/{org}/dependabot/alerts":                                                            {"$[].repository.full_name"},
	"GET /orgs/{org}/dependabot/repository-access":                                                 {"$.accessible_repositories[].full_name"},
	"GET /orgs/{org}/dependabot/secrets/{secret_name}/repositories":                                {"$.repositories[].full_name"},
	"GET /orgs/{org}/docker/conflicts":                                                             {"$[].repository.full_name"},
	"GET /orgs/{org}/events":                                                                       {"$[].payload.issue.repository.full_name", "$[].repo.name"},
	"GET /orgs/{org}/issues":                                                                       {"$[].repository.full_name"},
	"GET /orgs/{org}/members/{username}/codespaces":                                                {"$.codespaces[].repository.full_name"},
	"GET /orgs/{org}/migrations":                                                                   {"$[].repositories[].full_name"},
	"GET /orgs/{org}/migrations/{migration_id}":                                                    {"$.repositories[].full_name"},
	"GET /orgs/{org}/migrations/{migration_id}/repositories":                                       {"$[].full_name"},
	"GET /orgs/{org}/packages":                                                                     {"$[].repository.full_name"},
	"GET /orgs/{org}/packages/{package_type}/{package_name}":                                       {"$.repository.full_name"},
	"GET /orgs/{org}/personal-access-token-requests/{pat_request_id}/repositories":                 {"$[].full_name"},
	"GET /orgs/{org}/personal-access-tokens/{pat_id}/repositories":                                 {"$[].full_name"},
	"GET /orgs/{org}/repos":                                                                        {"$[].full_name"},
	"GET /orgs/{org}/secret-scanning/alerts":                                                       {"$[].repository.full_name"},
	"GET /orgs/{org}/security-advisories":                                                          {"$[].private_fork.full_name"},
	"GET /orgs/{org}/settings/immutable-releases/repositories":                                     {"$.repositories[].full_name"},
	"GET /orgs/{org}/teams/{team_slug}/repos":                                                      {"$[].full_name"},
	"GET /orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}":                                       {"$.full_name"},
	"GET /repos/{owner}/{repo}":                                                                    {"$.full_name"},
	"GET /repos/{owner}/{repo}/actions/cache/usage":                                                {"$.full_name"},
	"GET /repos/{owner}/{repo}/actions/runs":                                                       {"$.workflow_runs[].repository.full_name"},
	"GET /repos/{owner}/{repo}/actions/runs/{run_id}":                                              {"$.repository.full_name"},
	"GET /repos/{owner}/{repo}/actions/runs/{run_id}/attempts/{attempt_number}":                    {"$.repository.full_name"},
	"GET /repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs":                               {"$.workflow_runs[].repository.full_name"},
	"GET /repos/{owner}/{repo}/check-suites/{check_suite_id}":                                      {"$.repository.full_name"},
	"GET /repos/{owner}/{repo}/code-scanning/codeql/variant-analyses/{codeql_variant_analysis_id}": {"$.controller_repo.full_name", "$.scanned_repositories[].repository.full_name", "$.skipped_repositories.access_mismatch_repos.repositories[].full_name", "$.skipped_repositories.no_codeql_db_repos.repositories[].full_name", "$.skipped_repositories.over_limit_repos.repositories[].full_name"},
	"GET /repos/{owner}/{repo}/code-scanning/codeql/variant-analyses/{codeql_variant_analysis_id}/repos/{repo_owner}/{repo_name}": {"$.repository.full_name"},
	"GET /repos/{owner}/{repo}/codespaces":                                    {"$.codespaces[].repository.full_name"},
	"GET /repos/{owner}/{repo}/commits/{ref}/check-suites":                    {"$.check_suites[].repository.full_name"},
	"GET /repos/{owner}/{repo}/commits/{ref}/status":                          {"$.repository.full_name"},
	"GET /repos/{owner}/{repo}/events":                                        {"$[].payload.issue.repository.full_name", "$[].repo.name"},
	"GET /repos/{owner}/{repo}/forks":                                         {"$[].full_name"},
	"GET /repos/{owner}/{repo}/invitations":                                   {"$[].repository.full_name"},
	"GET /repos/{owner}/{repo}/issues":                                        {"$[].repository.full_name"},
	"GET /repos/{owner}/{repo}/issues/events":                                 {"$[].issue.repository.full_name"},
	"GET /repos/{owner}/{repo}/issues/events/{event_id}":                      {"$.issue.repository.full_name"},
	"GET /repos/{owner}/{repo}/issues/{issue_number}":                         {"$.repository.full_name"},
	"GET /repos/{owner}/{repo}/issues/{issue_number}/dependencies/blocked_by": {"$[].repository.full_name"},
	"GET /repos/{owner}/{repo}/issues/{issue_number}/dependencies/blocking":   {"$[].repository.full_name"},
	"GET /repos/{owner}/{repo}/issues/{issue_number}/parent":                  {"$.repository.full_name"},
	"GET /repos/{owner}/{repo}/issues/{issue_number}/sub_issues":              {"$[].repository.full_name"},
	"GET /repos/{owner}/{repo}/notifications":                                 {"$[].repository.full_name"},
	"GET /repos/{owner}/{repo}/security-advisories":                           {"$[].private_fork.full_name"},
	"GET /repos/{owner}/{repo}/security-advisories/{ghsa_id}":                 {"$.private_fork.full_name"},
	"GET /repositories":                                                       {"$[].full_name"},
	"GET /search/code":                                                        {"$.items[].repository.full_name"},
	"GET /search/commits":                                                     {"$.items[].repository.full_name"},
	"GET /search/issues":                                                      {"$.items[].repository.full_name"},
	"GET /search/repositories":                                                {"$.items[].full_name"},
	"GET /teams/{team_id}/repos":                                              {"$[].full_name"},
	"GET /teams/{team_id}/repos/{owner}/{repo}":                               {"$.full_name"},
	"GET /user/codespaces":                                                    {"$.codespaces[].repository.full_name"},
	"GET /user/codespaces/secrets/{secret_name}/repositories":                 {"$.repositories[].full_name"},
	"GET /user/codespaces/{codespace_name}":                                   {"$.repository.full_name"},
	"GET /user/docker/conflicts":                                              {"$[].repository.full_name"},
	"GET /user/installations/{installation_id}/repositories":                  {"$.repositories[].full_name"},
	"GET /user/issues":                                                        {"$[].repository.full_name"},
	"GET /user/migrations":                                                    {"$[].repositories[].full_name"},
	"GET /user/migrations/{migration_id}":                                     {"$.repositories[].full_name"},
	"GET /user/migrations/{migration_id}/repositories":                        {"$[].full_name"},
	"GET /user/packages":                                                      {"$[].repository.full_name"},
	"GET /user/packages/{package_type}/{package_name}":                        {"$.repository.full_name"},
	"GET /user/repos":                                                         {"$[].full_name"},
	"GET /user/repository_invitations":                                        {"$[].repository.full_name"},
	"GET /user/starred":                                                       {"$[].full_name"},
	"GET /user/subscriptions":                                                 {"$[].full_name"},
	"GET /users/{username}/docker/conflicts":                                  {"$[].repository.full_name"},
	"GET /users/{username}/events":                                            {"$[].payload.issue.repository.full_name", "$[].repo.name"},
	"GET /users/{username}/events/orgs/{org}":                                 {"$[].payload.issue.repository.full_name", "$[].repo.name"},
	"GET /users/{username}/events/public":                                     {"$[].payload.issue.repository.full_name", "$[].repo.name"},
	"GET /users/{username}/packages":                                          {"$[].repository.full_name"},
	"GET /users/{username}/packages/{package_type}/{package_name}":            {"$.repository.full_name"},
	"GET /users/{username}/received_events":                                   {"$[].payload.issue.repository.full_name", "$[].repo.name"},
	"GET /users/{username}/received_events/public":                            {"$[].payload.issue.repository.full_name", "$[].repo.name"},
	"GET /users/{username}/repos":                                             {"$[].full_name"},
	"GET /users/{username}/starred":                                           {"$[].full_name", "$[].repo.full_name"},
	"GET /users/{username}/subscriptions":                                     {"$[].full_name"},
}

// knownGetOps is every GET path template in the spec. A GET whose path matches none of
// these is off-spec and the filter fails closed (the spec is comprehensive).
var knownGetOps = []string{
	"/",
	"/advisories",
	"/advisories/{ghsa_id}",
	"/agents/repos/{owner}/{repo}/tasks",
	"/agents/repos/{owner}/{repo}/tasks/{task_id}",
	"/agents/tasks",
	"/agents/tasks/{task_id}",
	"/app",
	"/app/hook/config",
	"/app/hook/deliveries",
	"/app/hook/deliveries/{delivery_id}",
	"/app/installation-requests",
	"/app/installations",
	"/app/installations/{installation_id}",
	"/apps/{app_slug}",
	"/assignments/{assignment_id}",
	"/assignments/{assignment_id}/accepted_assignments",
	"/assignments/{assignment_id}/grades",
	"/classrooms",
	"/classrooms/{classroom_id}",
	"/classrooms/{classroom_id}/assignments",
	"/codes_of_conduct",
	"/codes_of_conduct/{key}",
	"/emojis",
	"/enterprises/{enterprise}/actions/cache/retention-limit",
	"/enterprises/{enterprise}/actions/cache/storage-limit",
	"/enterprises/{enterprise}/actions/oidc/customization/properties/repo",
	"/enterprises/{enterprise}/code-security/configurations",
	"/enterprises/{enterprise}/code-security/configurations/defaults",
	"/enterprises/{enterprise}/code-security/configurations/{configuration_id}",
	"/enterprises/{enterprise}/code-security/configurations/{configuration_id}/repositories",
	"/enterprises/{enterprise}/copilot/metrics/reports/enterprise-1-day",
	"/enterprises/{enterprise}/copilot/metrics/reports/enterprise-28-day/latest",
	"/enterprises/{enterprise}/copilot/metrics/reports/user-teams-1-day",
	"/enterprises/{enterprise}/copilot/metrics/reports/users-1-day",
	"/enterprises/{enterprise}/copilot/metrics/reports/users-28-day/latest",
	"/enterprises/{enterprise}/dependabot/alerts",
	"/enterprises/{enterprise}/dependabot/repository-access",
	"/enterprises/{enterprise}/teams",
	"/enterprises/{enterprise}/teams/{enterprise-team}/memberships",
	"/enterprises/{enterprise}/teams/{enterprise-team}/memberships/{username}",
	"/enterprises/{enterprise}/teams/{enterprise-team}/organizations",
	"/enterprises/{enterprise}/teams/{enterprise-team}/organizations/{org}",
	"/enterprises/{enterprise}/teams/{team_slug}",
	"/events",
	"/feeds",
	"/gists",
	"/gists/public",
	"/gists/starred",
	"/gists/{gist_id}",
	"/gists/{gist_id}/comments",
	"/gists/{gist_id}/comments/{comment_id}",
	"/gists/{gist_id}/commits",
	"/gists/{gist_id}/forks",
	"/gists/{gist_id}/star",
	"/gists/{gist_id}/{sha}",
	"/gitignore/templates",
	"/gitignore/templates/{name}",
	"/installation/repositories",
	"/issues",
	"/licenses",
	"/licenses/{license}",
	"/marketplace_listing/accounts/{account_id}",
	"/marketplace_listing/plans",
	"/marketplace_listing/plans/{plan_id}/accounts",
	"/marketplace_listing/stubbed/accounts/{account_id}",
	"/marketplace_listing/stubbed/plans",
	"/marketplace_listing/stubbed/plans/{plan_id}/accounts",
	"/meta",
	"/networks/{owner}/{repo}/events",
	"/notifications",
	"/notifications/threads/{thread_id}",
	"/notifications/threads/{thread_id}/subscription",
	"/octocat",
	"/organizations",
	"/organizations/{org}/actions/cache/retention-limit",
	"/organizations/{org}/actions/cache/storage-limit",
	"/organizations/{org}/settings/billing/ai_credit/usage",
	"/organizations/{org}/settings/billing/budgets",
	"/organizations/{org}/settings/billing/budgets/{budget_id}",
	"/organizations/{org}/settings/billing/premium_request/usage",
	"/organizations/{org}/settings/billing/usage",
	"/organizations/{org}/settings/billing/usage/summary",
	"/orgs/{org}",
	"/orgs/{org}/actions/cache/usage",
	"/orgs/{org}/actions/cache/usage-by-repository",
	"/orgs/{org}/actions/hosted-runners",
	"/orgs/{org}/actions/hosted-runners/images/custom",
	"/orgs/{org}/actions/hosted-runners/images/custom/{image_definition_id}",
	"/orgs/{org}/actions/hosted-runners/images/custom/{image_definition_id}/versions",
	"/orgs/{org}/actions/hosted-runners/images/custom/{image_definition_id}/versions/{version}",
	"/orgs/{org}/actions/hosted-runners/images/github-owned",
	"/orgs/{org}/actions/hosted-runners/images/partner",
	"/orgs/{org}/actions/hosted-runners/limits",
	"/orgs/{org}/actions/hosted-runners/machine-sizes",
	"/orgs/{org}/actions/hosted-runners/platforms",
	"/orgs/{org}/actions/hosted-runners/{hosted_runner_id}",
	"/orgs/{org}/actions/oidc/customization/properties/repo",
	"/orgs/{org}/actions/oidc/customization/sub",
	"/orgs/{org}/actions/permissions",
	"/orgs/{org}/actions/permissions/artifact-and-log-retention",
	"/orgs/{org}/actions/permissions/fork-pr-contributor-approval",
	"/orgs/{org}/actions/permissions/fork-pr-workflows-private-repos",
	"/orgs/{org}/actions/permissions/repositories",
	"/orgs/{org}/actions/permissions/selected-actions",
	"/orgs/{org}/actions/permissions/self-hosted-runners",
	"/orgs/{org}/actions/permissions/self-hosted-runners/repositories",
	"/orgs/{org}/actions/permissions/workflow",
	"/orgs/{org}/actions/runner-groups",
	"/orgs/{org}/actions/runner-groups/{runner_group_id}",
	"/orgs/{org}/actions/runner-groups/{runner_group_id}/hosted-runners",
	"/orgs/{org}/actions/runner-groups/{runner_group_id}/repositories",
	"/orgs/{org}/actions/runner-groups/{runner_group_id}/runners",
	"/orgs/{org}/actions/runners",
	"/orgs/{org}/actions/runners/downloads",
	"/orgs/{org}/actions/runners/{runner_id}",
	"/orgs/{org}/actions/runners/{runner_id}/labels",
	"/orgs/{org}/actions/secrets",
	"/orgs/{org}/actions/secrets/public-key",
	"/orgs/{org}/actions/secrets/{secret_name}",
	"/orgs/{org}/actions/secrets/{secret_name}/repositories",
	"/orgs/{org}/actions/variables",
	"/orgs/{org}/actions/variables/{name}",
	"/orgs/{org}/actions/variables/{name}/repositories",
	"/orgs/{org}/agents/secrets",
	"/orgs/{org}/agents/secrets/public-key",
	"/orgs/{org}/agents/secrets/{secret_name}",
	"/orgs/{org}/agents/secrets/{secret_name}/repositories",
	"/orgs/{org}/agents/variables",
	"/orgs/{org}/agents/variables/{name}",
	"/orgs/{org}/agents/variables/{name}/repositories",
	"/orgs/{org}/artifacts/{subject_digest}/metadata/deployment-records",
	"/orgs/{org}/artifacts/{subject_digest}/metadata/storage-records",
	"/orgs/{org}/attestations/repositories",
	"/orgs/{org}/attestations/{subject_digest}",
	"/orgs/{org}/blocks",
	"/orgs/{org}/blocks/{username}",
	"/orgs/{org}/campaigns",
	"/orgs/{org}/campaigns/{campaign_number}",
	"/orgs/{org}/code-scanning/alerts",
	"/orgs/{org}/code-security/configurations",
	"/orgs/{org}/code-security/configurations/defaults",
	"/orgs/{org}/code-security/configurations/{configuration_id}",
	"/orgs/{org}/code-security/configurations/{configuration_id}/repositories",
	"/orgs/{org}/codespaces",
	"/orgs/{org}/codespaces/secrets",
	"/orgs/{org}/codespaces/secrets/public-key",
	"/orgs/{org}/codespaces/secrets/{secret_name}",
	"/orgs/{org}/codespaces/secrets/{secret_name}/repositories",
	"/orgs/{org}/copilot-spaces",
	"/orgs/{org}/copilot-spaces/{space_number}",
	"/orgs/{org}/copilot-spaces/{space_number}/collaborators",
	"/orgs/{org}/copilot-spaces/{space_number}/resources",
	"/orgs/{org}/copilot-spaces/{space_number}/resources/{space_resource_id}",
	"/orgs/{org}/copilot/billing",
	"/orgs/{org}/copilot/billing/seats",
	"/orgs/{org}/copilot/coding-agent/permissions",
	"/orgs/{org}/copilot/coding-agent/permissions/repositories",
	"/orgs/{org}/copilot/content_exclusion",
	"/orgs/{org}/copilot/metrics",
	"/orgs/{org}/copilot/metrics/reports/organization-1-day",
	"/orgs/{org}/copilot/metrics/reports/organization-28-day/latest",
	"/orgs/{org}/copilot/metrics/reports/user-teams-1-day",
	"/orgs/{org}/copilot/metrics/reports/users-1-day",
	"/orgs/{org}/copilot/metrics/reports/users-28-day/latest",
	"/orgs/{org}/dependabot/alerts",
	"/orgs/{org}/dependabot/repository-access",
	"/orgs/{org}/dependabot/secrets",
	"/orgs/{org}/dependabot/secrets/public-key",
	"/orgs/{org}/dependabot/secrets/{secret_name}",
	"/orgs/{org}/dependabot/secrets/{secret_name}/repositories",
	"/orgs/{org}/docker/conflicts",
	"/orgs/{org}/events",
	"/orgs/{org}/failed_invitations",
	"/orgs/{org}/hooks",
	"/orgs/{org}/hooks/{hook_id}",
	"/orgs/{org}/hooks/{hook_id}/config",
	"/orgs/{org}/hooks/{hook_id}/deliveries",
	"/orgs/{org}/hooks/{hook_id}/deliveries/{delivery_id}",
	"/orgs/{org}/insights/api/route-stats/{actor_type}/{actor_id}",
	"/orgs/{org}/insights/api/subject-stats",
	"/orgs/{org}/insights/api/summary-stats",
	"/orgs/{org}/insights/api/summary-stats/users/{user_id}",
	"/orgs/{org}/insights/api/summary-stats/{actor_type}/{actor_id}",
	"/orgs/{org}/insights/api/time-stats",
	"/orgs/{org}/insights/api/time-stats/users/{user_id}",
	"/orgs/{org}/insights/api/time-stats/{actor_type}/{actor_id}",
	"/orgs/{org}/insights/api/user-stats/{user_id}",
	"/orgs/{org}/installation",
	"/orgs/{org}/installations",
	"/orgs/{org}/interaction-limits",
	"/orgs/{org}/invitations",
	"/orgs/{org}/invitations/{invitation_id}/teams",
	"/orgs/{org}/issue-fields",
	"/orgs/{org}/issue-types",
	"/orgs/{org}/issues",
	"/orgs/{org}/members",
	"/orgs/{org}/members/{username}",
	"/orgs/{org}/members/{username}/codespaces",
	"/orgs/{org}/members/{username}/copilot",
	"/orgs/{org}/memberships/{username}",
	"/orgs/{org}/migrations",
	"/orgs/{org}/migrations/{migration_id}",
	"/orgs/{org}/migrations/{migration_id}/archive",
	"/orgs/{org}/migrations/{migration_id}/repositories",
	"/orgs/{org}/organization-roles",
	"/orgs/{org}/organization-roles/{role_id}",
	"/orgs/{org}/organization-roles/{role_id}/teams",
	"/orgs/{org}/organization-roles/{role_id}/users",
	"/orgs/{org}/outside_collaborators",
	"/orgs/{org}/packages",
	"/orgs/{org}/packages/{package_type}/{package_name}",
	"/orgs/{org}/packages/{package_type}/{package_name}/versions",
	"/orgs/{org}/packages/{package_type}/{package_name}/versions/{package_version_id}",
	"/orgs/{org}/personal-access-token-requests",
	"/orgs/{org}/personal-access-token-requests/{pat_request_id}/repositories",
	"/orgs/{org}/personal-access-tokens",
	"/orgs/{org}/personal-access-tokens/{pat_id}/repositories",
	"/orgs/{org}/private-registries",
	"/orgs/{org}/private-registries/public-key",
	"/orgs/{org}/private-registries/{secret_name}",
	"/orgs/{org}/projectsV2",
	"/orgs/{org}/projectsV2/{project_number}",
	"/orgs/{org}/projectsV2/{project_number}/fields",
	"/orgs/{org}/projectsV2/{project_number}/fields/{field_id}",
	"/orgs/{org}/projectsV2/{project_number}/items",
	"/orgs/{org}/projectsV2/{project_number}/items/{item_id}",
	"/orgs/{org}/projectsV2/{project_number}/views/{view_number}/items",
	"/orgs/{org}/properties/schema",
	"/orgs/{org}/properties/schema/{custom_property_name}",
	"/orgs/{org}/properties/values",
	"/orgs/{org}/public_members",
	"/orgs/{org}/public_members/{username}",
	"/orgs/{org}/repos",
	"/orgs/{org}/rulesets",
	"/orgs/{org}/rulesets/rule-suites",
	"/orgs/{org}/rulesets/rule-suites/{rule_suite_id}",
	"/orgs/{org}/rulesets/{ruleset_id}",
	"/orgs/{org}/rulesets/{ruleset_id}/history",
	"/orgs/{org}/rulesets/{ruleset_id}/history/{version_id}",
	"/orgs/{org}/secret-scanning/alerts",
	"/orgs/{org}/secret-scanning/pattern-configurations",
	"/orgs/{org}/security-advisories",
	"/orgs/{org}/security-managers",
	"/orgs/{org}/settings/immutable-releases",
	"/orgs/{org}/settings/immutable-releases/repositories",
	"/orgs/{org}/settings/network-configurations",
	"/orgs/{org}/settings/network-configurations/{network_configuration_id}",
	"/orgs/{org}/settings/network-settings/{network_settings_id}",
	"/orgs/{org}/team/{team_slug}/copilot/metrics",
	"/orgs/{org}/teams",
	"/orgs/{org}/teams/{team_slug}",
	"/orgs/{org}/teams/{team_slug}/invitations",
	"/orgs/{org}/teams/{team_slug}/members",
	"/orgs/{org}/teams/{team_slug}/memberships/{username}",
	"/orgs/{org}/teams/{team_slug}/repos",
	"/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}",
	"/orgs/{org}/teams/{team_slug}/teams",
	"/rate_limit",
	"/repos/{owner}/{repo}",
	"/repos/{owner}/{repo}/actions/artifacts",
	"/repos/{owner}/{repo}/actions/artifacts/{artifact_id}",
	"/repos/{owner}/{repo}/actions/artifacts/{artifact_id}/{archive_format}",
	"/repos/{owner}/{repo}/actions/cache/retention-limit",
	"/repos/{owner}/{repo}/actions/cache/storage-limit",
	"/repos/{owner}/{repo}/actions/cache/usage",
	"/repos/{owner}/{repo}/actions/caches",
	"/repos/{owner}/{repo}/actions/concurrency_groups",
	"/repos/{owner}/{repo}/actions/concurrency_groups/{concurrency_group_name}",
	"/repos/{owner}/{repo}/actions/jobs/{job_id}",
	"/repos/{owner}/{repo}/actions/jobs/{job_id}/logs",
	"/repos/{owner}/{repo}/actions/oidc/customization/sub",
	"/repos/{owner}/{repo}/actions/organization-secrets",
	"/repos/{owner}/{repo}/actions/organization-variables",
	"/repos/{owner}/{repo}/actions/permissions",
	"/repos/{owner}/{repo}/actions/permissions/access",
	"/repos/{owner}/{repo}/actions/permissions/artifact-and-log-retention",
	"/repos/{owner}/{repo}/actions/permissions/fork-pr-contributor-approval",
	"/repos/{owner}/{repo}/actions/permissions/fork-pr-workflows-private-repos",
	"/repos/{owner}/{repo}/actions/permissions/selected-actions",
	"/repos/{owner}/{repo}/actions/permissions/workflow",
	"/repos/{owner}/{repo}/actions/runners",
	"/repos/{owner}/{repo}/actions/runners/downloads",
	"/repos/{owner}/{repo}/actions/runners/{runner_id}",
	"/repos/{owner}/{repo}/actions/runners/{runner_id}/labels",
	"/repos/{owner}/{repo}/actions/runs",
	"/repos/{owner}/{repo}/actions/runs/{run_id}",
	"/repos/{owner}/{repo}/actions/runs/{run_id}/approvals",
	"/repos/{owner}/{repo}/actions/runs/{run_id}/artifacts",
	"/repos/{owner}/{repo}/actions/runs/{run_id}/attempts/{attempt_number}",
	"/repos/{owner}/{repo}/actions/runs/{run_id}/attempts/{attempt_number}/jobs",
	"/repos/{owner}/{repo}/actions/runs/{run_id}/attempts/{attempt_number}/logs",
	"/repos/{owner}/{repo}/actions/runs/{run_id}/concurrency_groups",
	"/repos/{owner}/{repo}/actions/runs/{run_id}/jobs",
	"/repos/{owner}/{repo}/actions/runs/{run_id}/logs",
	"/repos/{owner}/{repo}/actions/runs/{run_id}/pending_deployments",
	"/repos/{owner}/{repo}/actions/runs/{run_id}/timing",
	"/repos/{owner}/{repo}/actions/secrets",
	"/repos/{owner}/{repo}/actions/secrets/public-key",
	"/repos/{owner}/{repo}/actions/secrets/{secret_name}",
	"/repos/{owner}/{repo}/actions/variables",
	"/repos/{owner}/{repo}/actions/variables/{name}",
	"/repos/{owner}/{repo}/actions/workflows",
	"/repos/{owner}/{repo}/actions/workflows/{workflow_id}",
	"/repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs",
	"/repos/{owner}/{repo}/actions/workflows/{workflow_id}/timing",
	"/repos/{owner}/{repo}/activity",
	"/repos/{owner}/{repo}/agents/organization-secrets",
	"/repos/{owner}/{repo}/agents/organization-variables",
	"/repos/{owner}/{repo}/agents/secrets",
	"/repos/{owner}/{repo}/agents/secrets/public-key",
	"/repos/{owner}/{repo}/agents/secrets/{secret_name}",
	"/repos/{owner}/{repo}/agents/variables",
	"/repos/{owner}/{repo}/agents/variables/{name}",
	"/repos/{owner}/{repo}/assignees",
	"/repos/{owner}/{repo}/assignees/{assignee}",
	"/repos/{owner}/{repo}/attestations/{subject_digest}",
	"/repos/{owner}/{repo}/autolinks",
	"/repos/{owner}/{repo}/autolinks/{autolink_id}",
	"/repos/{owner}/{repo}/automated-security-fixes",
	"/repos/{owner}/{repo}/branches",
	"/repos/{owner}/{repo}/branches/{branch}",
	"/repos/{owner}/{repo}/branches/{branch}/protection",
	"/repos/{owner}/{repo}/branches/{branch}/protection/enforce_admins",
	"/repos/{owner}/{repo}/branches/{branch}/protection/required_pull_request_reviews",
	"/repos/{owner}/{repo}/branches/{branch}/protection/required_signatures",
	"/repos/{owner}/{repo}/branches/{branch}/protection/required_status_checks",
	"/repos/{owner}/{repo}/branches/{branch}/protection/required_status_checks/contexts",
	"/repos/{owner}/{repo}/branches/{branch}/protection/restrictions",
	"/repos/{owner}/{repo}/branches/{branch}/protection/restrictions/apps",
	"/repos/{owner}/{repo}/branches/{branch}/protection/restrictions/teams",
	"/repos/{owner}/{repo}/branches/{branch}/protection/restrictions/users",
	"/repos/{owner}/{repo}/check-runs/{check_run_id}",
	"/repos/{owner}/{repo}/check-runs/{check_run_id}/annotations",
	"/repos/{owner}/{repo}/check-suites/{check_suite_id}",
	"/repos/{owner}/{repo}/check-suites/{check_suite_id}/check-runs",
	"/repos/{owner}/{repo}/code-quality/setup",
	"/repos/{owner}/{repo}/code-scanning/alerts",
	"/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}",
	"/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/autofix",
	"/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/instances",
	"/repos/{owner}/{repo}/code-scanning/analyses",
	"/repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}",
	"/repos/{owner}/{repo}/code-scanning/codeql/databases",
	"/repos/{owner}/{repo}/code-scanning/codeql/databases/{language}",
	"/repos/{owner}/{repo}/code-scanning/codeql/variant-analyses/{codeql_variant_analysis_id}",
	"/repos/{owner}/{repo}/code-scanning/codeql/variant-analyses/{codeql_variant_analysis_id}/repos/{repo_owner}/{repo_name}",
	"/repos/{owner}/{repo}/code-scanning/default-setup",
	"/repos/{owner}/{repo}/code-scanning/sarifs/{sarif_id}",
	"/repos/{owner}/{repo}/code-security-configuration",
	"/repos/{owner}/{repo}/codeowners/errors",
	"/repos/{owner}/{repo}/codespaces",
	"/repos/{owner}/{repo}/codespaces/devcontainers",
	"/repos/{owner}/{repo}/codespaces/machines",
	"/repos/{owner}/{repo}/codespaces/new",
	"/repos/{owner}/{repo}/codespaces/permissions_check",
	"/repos/{owner}/{repo}/codespaces/secrets",
	"/repos/{owner}/{repo}/codespaces/secrets/public-key",
	"/repos/{owner}/{repo}/codespaces/secrets/{secret_name}",
	"/repos/{owner}/{repo}/collaborators",
	"/repos/{owner}/{repo}/collaborators/{username}",
	"/repos/{owner}/{repo}/collaborators/{username}/permission",
	"/repos/{owner}/{repo}/comments",
	"/repos/{owner}/{repo}/comments/{comment_id}",
	"/repos/{owner}/{repo}/comments/{comment_id}/reactions",
	"/repos/{owner}/{repo}/commits",
	"/repos/{owner}/{repo}/commits/{commit_sha}/branches-where-head",
	"/repos/{owner}/{repo}/commits/{commit_sha}/comments",
	"/repos/{owner}/{repo}/commits/{commit_sha}/pulls",
	"/repos/{owner}/{repo}/commits/{ref}",
	"/repos/{owner}/{repo}/commits/{ref}/check-runs",
	"/repos/{owner}/{repo}/commits/{ref}/check-suites",
	"/repos/{owner}/{repo}/commits/{ref}/status",
	"/repos/{owner}/{repo}/commits/{ref}/statuses",
	"/repos/{owner}/{repo}/community/profile",
	"/repos/{owner}/{repo}/compare/{basehead}",
	"/repos/{owner}/{repo}/contents/{path}",
	"/repos/{owner}/{repo}/contributors",
	"/repos/{owner}/{repo}/copilot/cloud-agent/configuration",
	"/repos/{owner}/{repo}/dependabot/alerts",
	"/repos/{owner}/{repo}/dependabot/alerts/{alert_number}",
	"/repos/{owner}/{repo}/dependabot/secrets",
	"/repos/{owner}/{repo}/dependabot/secrets/public-key",
	"/repos/{owner}/{repo}/dependabot/secrets/{secret_name}",
	"/repos/{owner}/{repo}/dependency-graph/compare/{basehead}",
	"/repos/{owner}/{repo}/dependency-graph/sbom",
	"/repos/{owner}/{repo}/dependency-graph/sbom/fetch-report/{sbom_uuid}",
	"/repos/{owner}/{repo}/dependency-graph/sbom/generate-report",
	"/repos/{owner}/{repo}/deployments",
	"/repos/{owner}/{repo}/deployments/{deployment_id}",
	"/repos/{owner}/{repo}/deployments/{deployment_id}/statuses",
	"/repos/{owner}/{repo}/deployments/{deployment_id}/statuses/{status_id}",
	"/repos/{owner}/{repo}/environments",
	"/repos/{owner}/{repo}/environments/{environment_name}",
	"/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies",
	"/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies/{branch_policy_id}",
	"/repos/{owner}/{repo}/environments/{environment_name}/deployment_protection_rules",
	"/repos/{owner}/{repo}/environments/{environment_name}/deployment_protection_rules/apps",
	"/repos/{owner}/{repo}/environments/{environment_name}/deployment_protection_rules/{protection_rule_id}",
	"/repos/{owner}/{repo}/environments/{environment_name}/secrets",
	"/repos/{owner}/{repo}/environments/{environment_name}/secrets/public-key",
	"/repos/{owner}/{repo}/environments/{environment_name}/secrets/{secret_name}",
	"/repos/{owner}/{repo}/environments/{environment_name}/variables",
	"/repos/{owner}/{repo}/environments/{environment_name}/variables/{name}",
	"/repos/{owner}/{repo}/events",
	"/repos/{owner}/{repo}/forks",
	"/repos/{owner}/{repo}/git/blobs/{file_sha}",
	"/repos/{owner}/{repo}/git/commits/{commit_sha}",
	"/repos/{owner}/{repo}/git/matching-refs/{ref}",
	"/repos/{owner}/{repo}/git/ref/{ref}",
	"/repos/{owner}/{repo}/git/tags/{tag_sha}",
	"/repos/{owner}/{repo}/git/trees/{tree_sha}",
	"/repos/{owner}/{repo}/hash-algorithm",
	"/repos/{owner}/{repo}/hooks",
	"/repos/{owner}/{repo}/hooks/{hook_id}",
	"/repos/{owner}/{repo}/hooks/{hook_id}/config",
	"/repos/{owner}/{repo}/hooks/{hook_id}/deliveries",
	"/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}",
	"/repos/{owner}/{repo}/immutable-releases",
	"/repos/{owner}/{repo}/import",
	"/repos/{owner}/{repo}/import/authors",
	"/repos/{owner}/{repo}/import/large_files",
	"/repos/{owner}/{repo}/installation",
	"/repos/{owner}/{repo}/interaction-limits",
	"/repos/{owner}/{repo}/invitations",
	"/repos/{owner}/{repo}/issues",
	"/repos/{owner}/{repo}/issues/comments",
	"/repos/{owner}/{repo}/issues/comments/{comment_id}",
	"/repos/{owner}/{repo}/issues/comments/{comment_id}/reactions",
	"/repos/{owner}/{repo}/issues/events",
	"/repos/{owner}/{repo}/issues/events/{event_id}",
	"/repos/{owner}/{repo}/issues/{issue_number}",
	"/repos/{owner}/{repo}/issues/{issue_number}/assignees/{assignee}",
	"/repos/{owner}/{repo}/issues/{issue_number}/comments",
	"/repos/{owner}/{repo}/issues/{issue_number}/dependencies/blocked_by",
	"/repos/{owner}/{repo}/issues/{issue_number}/dependencies/blocking",
	"/repos/{owner}/{repo}/issues/{issue_number}/events",
	"/repos/{owner}/{repo}/issues/{issue_number}/issue-field-values",
	"/repos/{owner}/{repo}/issues/{issue_number}/labels",
	"/repos/{owner}/{repo}/issues/{issue_number}/parent",
	"/repos/{owner}/{repo}/issues/{issue_number}/reactions",
	"/repos/{owner}/{repo}/issues/{issue_number}/sub_issues",
	"/repos/{owner}/{repo}/issues/{issue_number}/timeline",
	"/repos/{owner}/{repo}/keys",
	"/repos/{owner}/{repo}/keys/{key_id}",
	"/repos/{owner}/{repo}/labels",
	"/repos/{owner}/{repo}/labels/{name}",
	"/repos/{owner}/{repo}/languages",
	"/repos/{owner}/{repo}/license",
	"/repos/{owner}/{repo}/milestones",
	"/repos/{owner}/{repo}/milestones/{milestone_number}",
	"/repos/{owner}/{repo}/milestones/{milestone_number}/labels",
	"/repos/{owner}/{repo}/notifications",
	"/repos/{owner}/{repo}/pages",
	"/repos/{owner}/{repo}/pages/builds",
	"/repos/{owner}/{repo}/pages/builds/latest",
	"/repos/{owner}/{repo}/pages/builds/{build_id}",
	"/repos/{owner}/{repo}/pages/deployments/{pages_deployment_id}",
	"/repos/{owner}/{repo}/pages/health",
	"/repos/{owner}/{repo}/private-vulnerability-reporting",
	"/repos/{owner}/{repo}/properties/values",
	"/repos/{owner}/{repo}/pulls",
	"/repos/{owner}/{repo}/pulls/comments",
	"/repos/{owner}/{repo}/pulls/comments/{comment_id}",
	"/repos/{owner}/{repo}/pulls/comments/{comment_id}/reactions",
	"/repos/{owner}/{repo}/pulls/{pull_number}",
	"/repos/{owner}/{repo}/pulls/{pull_number}/comments",
	"/repos/{owner}/{repo}/pulls/{pull_number}/commits",
	"/repos/{owner}/{repo}/pulls/{pull_number}/files",
	"/repos/{owner}/{repo}/pulls/{pull_number}/merge",
	"/repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers",
	"/repos/{owner}/{repo}/pulls/{pull_number}/reviews",
	"/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}",
	"/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}/comments",
	"/repos/{owner}/{repo}/readme",
	"/repos/{owner}/{repo}/readme/{dir}",
	"/repos/{owner}/{repo}/releases",
	"/repos/{owner}/{repo}/releases/assets/{asset_id}",
	"/repos/{owner}/{repo}/releases/latest",
	"/repos/{owner}/{repo}/releases/tags/{tag}",
	"/repos/{owner}/{repo}/releases/{release_id}",
	"/repos/{owner}/{repo}/releases/{release_id}/assets",
	"/repos/{owner}/{repo}/releases/{release_id}/reactions",
	"/repos/{owner}/{repo}/rules/branches/{branch}",
	"/repos/{owner}/{repo}/rulesets",
	"/repos/{owner}/{repo}/rulesets/rule-suites",
	"/repos/{owner}/{repo}/rulesets/rule-suites/{rule_suite_id}",
	"/repos/{owner}/{repo}/rulesets/{ruleset_id}",
	"/repos/{owner}/{repo}/rulesets/{ruleset_id}/history",
	"/repos/{owner}/{repo}/rulesets/{ruleset_id}/history/{version_id}",
	"/repos/{owner}/{repo}/secret-scanning/alerts",
	"/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}",
	"/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}/locations",
	"/repos/{owner}/{repo}/secret-scanning/scan-history",
	"/repos/{owner}/{repo}/security-advisories",
	"/repos/{owner}/{repo}/security-advisories/{ghsa_id}",
	"/repos/{owner}/{repo}/stargazers",
	"/repos/{owner}/{repo}/stats/code_frequency",
	"/repos/{owner}/{repo}/stats/commit_activity",
	"/repos/{owner}/{repo}/stats/contributors",
	"/repos/{owner}/{repo}/stats/participation",
	"/repos/{owner}/{repo}/stats/punch_card",
	"/repos/{owner}/{repo}/subscribers",
	"/repos/{owner}/{repo}/subscription",
	"/repos/{owner}/{repo}/tags",
	"/repos/{owner}/{repo}/tarball/{ref}",
	"/repos/{owner}/{repo}/teams",
	"/repos/{owner}/{repo}/topics",
	"/repos/{owner}/{repo}/traffic/clones",
	"/repos/{owner}/{repo}/traffic/popular/paths",
	"/repos/{owner}/{repo}/traffic/popular/referrers",
	"/repos/{owner}/{repo}/traffic/views",
	"/repos/{owner}/{repo}/vulnerability-alerts",
	"/repos/{owner}/{repo}/zipball/{ref}",
	"/repositories",
	"/search/code",
	"/search/commits",
	"/search/issues",
	"/search/labels",
	"/search/repositories",
	"/search/topics",
	"/search/users",
	"/teams/{team_id}",
	"/teams/{team_id}/invitations",
	"/teams/{team_id}/members",
	"/teams/{team_id}/members/{username}",
	"/teams/{team_id}/memberships/{username}",
	"/teams/{team_id}/repos",
	"/teams/{team_id}/repos/{owner}/{repo}",
	"/teams/{team_id}/teams",
	"/user",
	"/user/blocks",
	"/user/blocks/{username}",
	"/user/codespaces",
	"/user/codespaces/secrets",
	"/user/codespaces/secrets/public-key",
	"/user/codespaces/secrets/{secret_name}",
	"/user/codespaces/secrets/{secret_name}/repositories",
	"/user/codespaces/{codespace_name}",
	"/user/codespaces/{codespace_name}/exports/{export_id}",
	"/user/codespaces/{codespace_name}/machines",
	"/user/docker/conflicts",
	"/user/emails",
	"/user/followers",
	"/user/following",
	"/user/following/{username}",
	"/user/gpg_keys",
	"/user/gpg_keys/{gpg_key_id}",
	"/user/installations",
	"/user/installations/{installation_id}/repositories",
	"/user/interaction-limits",
	"/user/issues",
	"/user/keys",
	"/user/keys/{key_id}",
	"/user/marketplace_purchases",
	"/user/marketplace_purchases/stubbed",
	"/user/memberships/orgs",
	"/user/memberships/orgs/{org}",
	"/user/migrations",
	"/user/migrations/{migration_id}",
	"/user/migrations/{migration_id}/archive",
	"/user/migrations/{migration_id}/repositories",
	"/user/orgs",
	"/user/packages",
	"/user/packages/{package_type}/{package_name}",
	"/user/packages/{package_type}/{package_name}/versions",
	"/user/packages/{package_type}/{package_name}/versions/{package_version_id}",
	"/user/public_emails",
	"/user/repos",
	"/user/repository_invitations",
	"/user/social_accounts",
	"/user/ssh_signing_keys",
	"/user/ssh_signing_keys/{ssh_signing_key_id}",
	"/user/starred",
	"/user/starred/{owner}/{repo}",
	"/user/subscriptions",
	"/user/teams",
	"/user/{account_id}",
	"/users",
	"/users/{username}",
	"/users/{username}/attestations/{subject_digest}",
	"/users/{username}/copilot-spaces",
	"/users/{username}/copilot-spaces/{space_number}",
	"/users/{username}/copilot-spaces/{space_number}/collaborators",
	"/users/{username}/copilot-spaces/{space_number}/resources",
	"/users/{username}/copilot-spaces/{space_number}/resources/{space_resource_id}",
	"/users/{username}/docker/conflicts",
	"/users/{username}/events",
	"/users/{username}/events/orgs/{org}",
	"/users/{username}/events/public",
	"/users/{username}/followers",
	"/users/{username}/following",
	"/users/{username}/following/{target_user}",
	"/users/{username}/gists",
	"/users/{username}/gpg_keys",
	"/users/{username}/hovercard",
	"/users/{username}/installation",
	"/users/{username}/keys",
	"/users/{username}/orgs",
	"/users/{username}/packages",
	"/users/{username}/packages/{package_type}/{package_name}",
	"/users/{username}/packages/{package_type}/{package_name}/versions",
	"/users/{username}/packages/{package_type}/{package_name}/versions/{package_version_id}",
	"/users/{username}/projectsV2",
	"/users/{username}/projectsV2/{project_number}",
	"/users/{username}/projectsV2/{project_number}/fields",
	"/users/{username}/projectsV2/{project_number}/fields/{field_id}",
	"/users/{username}/projectsV2/{project_number}/items",
	"/users/{username}/projectsV2/{project_number}/items/{item_id}",
	"/users/{username}/projectsV2/{project_number}/views/{view_number}/items",
	"/users/{username}/received_events",
	"/users/{username}/received_events/public",
	"/users/{username}/repos",
	"/users/{username}/settings/billing/ai_credit/usage",
	"/users/{username}/settings/billing/premium_request/usage",
	"/users/{username}/settings/billing/usage",
	"/users/{username}/settings/billing/usage/summary",
	"/users/{username}/social_accounts",
	"/users/{username}/ssh_signing_keys",
	"/users/{username}/starred",
	"/users/{username}/subscriptions",
	"/versions",
	"/zen",
}
